fastlane_version '2.2.1'

# before_all do
#   ensure_git_branch
#   ensure_git_status_clean
#   git_pull
# end

platform :ios do
   # iOS Lanes
end


# desc 'Fetch certificates and provisioning profiles'
# lane :certificates do
#   match(app_identifier: 'com.app.bundle', type: 'development', readonly: true)
#   match(app_identifier: 'com.app.bundle', type: 'appstore', readonly: true)
# end

# increment code,
# clean build
# ship to beta
platform :android do
  desc "Android build and release to beta"
  lane :beta do
    increment_version_code(app_project_dir: './android/app')    
    gradle(task: 'clean', project_dir: './android/')
    gradle(task: 'bundle', build_type 'Release', project_dir: './android')
    supplu(track:'beta',aab:'./android/app/build/outputs/bundle/release/app-release.aab')
  
  end
 end